FROM mcr.microsoft.com/dotnet/core/sdk:3.1-alpine AS build
WORKDIR /app

COPY run.sh /opt/test-runner/bin/

# Copy csproj and restore as distinct layers
COPY src/Exercism.TestRunner.CSharp/Exercism.TestRunner.CSharp.csproj ./
RUN dotnet restore

# Copy everything else and build
COPY src/Exercism.TestRunner.CSharp/ ./
RUN dotnet publish -r linux-musl-x64 -c Release -o /opt/test-runner

# Build runtime image
FROM mcr.microsoft.com/dotnet/core/sdk:3.1-alpine AS runtime
WORKDIR /opt/test-runner
COPY --from=build /opt/test-runner/ .

# Install Ruby
RUN apk add build-base ruby ruby-dev 

# Install the gems for the Ruby webserver
RUN gem install json sinatra sinatra-contrib puma etc

# Add the Ruby server
COPY server.rb .

ENTRYPOINT [ "ruby", "server.rb", "-o", "0.0.0.0" ]
